document.addEventListener('DOMContentLoaded',()=>{if(document.querySelector('.site-menu'))return;
const groups=[
 {title:'Le voyage',items:[['01','♡','Les voyageurs','voyageurs.html'],['02','↗','Les trajets','trajets.html'],['03','✦','Les activités','activites.html'],['04','◷','Les journées','journees.html'],['05','⌂','Le logement','logement.html'],['06','£','Le budget','payer-londres.html']]},
 {title:'À préparer',items:[['07','Aa','Parler anglais à Londres','anglais.html'],['08','☂','Guide pratique','survivre-londres.html'],['09','▱','Nos valises','valises.html']]},
 {title:'Londres en images',items:[['10','◌','London mood','london-mood.html'],['11','✿','Pinterest · Cozy · TikTok','pinterest-cozy.html']]}
];
const b=document.createElement('button');b.className='site-menu';b.id='site-menu-toggle';b.setAttribute('aria-label','Ouvrir le menu');b.innerHTML='<span class="menu-lines"><i></i><i></i></span><span class="menu-label">Menu</span>';
const o=document.createElement('div');o.className='site-menu-overlay';
const p=document.createElement('aside');p.className='site-menu-panel';p.setAttribute('aria-hidden','true');
p.innerHTML='<button class="site-menu-close" aria-label="Fermer">×</button><div class="site-menu-head"><div class="site-menu-kicker">London · October 2026</div><div class="site-menu-title">Notre<br><em>voyage</em></div><p>22 — 29 octobre · 3 voyageuses</p></div><nav></nav><div class="site-menu-foot">London Autumn ’26 <span>♡</span></div>';
const n=p.querySelector('nav');
groups.forEach(g=>{const s=document.createElement('section');s.innerHTML='<div class="site-menu-group">'+g.title+'</div>';const list=document.createElement('div');list.className='site-menu-links';g.items.forEach(([num,icon,label,url])=>{const a=document.createElement('a');a.href=url;a.innerHTML='<span class="menu-num">'+num+'</span><span class="menu-icon">'+icon+'</span><span class="menu-text">'+label+'</span><span class="menu-arrow">↗</span>';list.appendChild(a)});s.appendChild(list);n.appendChild(s)});
const css=document.createElement('style');css.textContent=`
.site-menu{position:fixed;z-index:10001;top:18px;left:18px;width:66px;height:66px;border:1px solid rgba(239,231,216,.35);border-radius:50%;background:#213a2eee;color:#efe7d8;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;cursor:pointer;box-shadow:0 12px 32px #17130e55;backdrop-filter:blur(8px);transition:.28s ease}
.site-menu:hover{transform:translateY(-2px);background:#294735}.menu-lines{display:flex;flex-direction:column;gap:4px}.menu-lines i{display:block;width:17px;height:1px;background:#efe7d8}.menu-label{font:500 8px/1 'DM Sans',sans-serif;letter-spacing:.15em;text-transform:uppercase}
.site-menu-overlay{position:fixed;z-index:10000;inset:0;background:rgba(22,20,17,.48);opacity:0;visibility:hidden;backdrop-filter:blur(2px);transition:opacity .3s ease,visibility .3s ease}.site-menu-overlay.open{opacity:1;visibility:visible}
.site-menu-panel{position:fixed;z-index:10002;left:0;top:0;bottom:0;width:min(465px,91vw);background:#f3ecdf;color:#2f2a22;padding:34px 30px 24px;overflow:auto;box-shadow:20px 0 65px #1a151044;transform:translateX(-102%);transition:transform .46s cubic-bezier(.22,.61,.36,1)}
.site-menu-panel.open{transform:translateX(0)}.site-menu-close{position:absolute;right:22px;top:20px;width:42px;height:42px;border:1px solid #d2c0a7;background:transparent;border-radius:50%;font:300 25px/1 'Cormorant Garamond';color:#243f32;cursor:pointer}
.site-menu-head{padding:16px 42px 27px 2px;border-bottom:1px solid #d2c0a7}.site-menu-kicker,.site-menu-group{font:500 9px/1 'DM Sans',sans-serif;letter-spacing:.18em;text-transform:uppercase;color:#a55d35}.site-menu-title{font:600 54px/.82 'Cormorant Garamond';color:#243f32;margin:12px 0}.site-menu-title em{font-weight:500;color:#a55d35}.site-menu-head p{font:11px/1.5 'DM Sans',sans-serif;color:#756d61;margin:0}
.site-menu-panel nav{padding-top:21px}.site-menu-panel section{margin-bottom:23px}.site-menu-group{margin:0 2px 9px;color:#7a7165}
.site-menu-links{display:grid;gap:3px}.site-menu-links a{display:grid;grid-template-columns:28px 27px 1fr 18px;align-items:center;gap:7px;padding:10px 8px;text-decoration:none;color:#302b24;border-bottom:1px solid #d2c0a766;transition:.22s ease}.site-menu-links a:hover{background:#e8dfd1;transform:translateX(5px)}.menu-num{font:500 9px 'DM Sans';color:#a55d35;letter-spacing:.08em}.menu-icon{font:18px/1 'Cormorant Garamond';color:#243f32;text-align:center}.menu-text{font:500 17px 'Cormorant Garamond';color:#243f32}.menu-arrow{font:14px 'DM Sans';color:#a55d35;text-align:right;opacity:.55}.site-menu-foot{margin-top:14px;padding-top:16px;border-top:1px solid #d2c0a7;font:500 9px 'DM Sans';letter-spacing:.16em;text-transform:uppercase;color:#7a7165;display:flex;justify-content:space-between}.site-menu-foot span{font-size:15px;color:#a55d35}
@media(max-width:760px){.site-menu{top:13px;left:13px;width:58px;height:58px}.site-menu-panel{padding:28px 20px 22px}.site-menu-title{font-size:48px}.site-menu-links a{padding:11px 6px}.menu-text{font-size:16px}}
`;document.head.appendChild(css);document.body.append(b,o,p);
const open=()=>{o.classList.add('open');p.classList.add('open');p.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};
const close=()=>{o.classList.remove('open');p.classList.remove('open');p.setAttribute('aria-hidden','true');document.body.style.overflow=''};
b.onclick=open;o.onclick=e=>{if(e.target===o)close()};p.querySelector('.site-menu-close').onclick=close;p.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
});